# Generated by Django 5.2 on 2025-05-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Municipio',
            new_name='Provincia',
        ),
        migrations.RenameField(
            model_name='institucion',
            old_name='municipio',
            new_name='provincia',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='id_municipio',
            new_name='id_provincia',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='nombre_municipio',
            new_name='nombre_provincia',
        ),
    ]
