# Generated by Django 5.2 on 2025-05-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_rename_municipio_provincia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institucion',
        ),
    ]
