# Generated by Django 5.2 on 2025-05-13 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_delete_institucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_institucion', models.CharField(max_length=30)),
                ('codigo_institucion', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('email_institucion', models.EmailField(help_text='Correo electrónico de la institucion', max_length=30)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.provincia')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre_institucion'],
            },
        ),
    ]
