# Generated by Django 5.2 on 2025-05-15 19:06

from django.db import migrations

def forwards(apps, schema_editor):
    NivelEducativo = apps.get_model('education', 'NivelEducativo')
    #Migración para la tabla NivelEducativo
    niveles = [
        {'nivel_educativo': 'Primaria'},
        {'nivel_educativo': 'Secundaria'},
        {'nivel_educativo': 'Bachillerato'},
        {'nivel_educativo': 'Superior'},
    ]
    for nivel_data in niveles:
        NivelEducativo.objects.create(**nivel_data)

def backwards(apps, schema_editor):
    NivelEducativo = apps.get_model('education', 'NivelEducativo')
    niveles_a_eliminar = ['Primaria', 'Secundaria', 'Bachillerato', 'Superior']
    NivelEducativo.objects.filter(nivel_educativo__in=niveles_a_eliminar).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_institucion'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
