# Generated by Django 5.2 on 2025-05-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20250515_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institucion',
        ),
    ]
