# Generated by Django 5.2 on 2025-06-06 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0007_tiporecurso_recurso"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurso",
            name="archivo_recurso",
        ),
        migrations.AddField(
            model_name="seccion",
            name="contenido_seccion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contenido",
                to="education.recurso",
            ),
        ),
        migrations.AddField(
            model_name="seccion",
            name="instruccion_ejecutor_seccion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instruccion",
                to="education.recurso",
            ),
        ),
        migrations.AddField(
            model_name="seccion",
            name="video_seccion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video",
                to="education.recurso",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="dificultad_curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="education.dificultadcurso",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="idioma_curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="education.idioma",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="modulo_curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="education.modulo",
            ),
        ),
        migrations.AlterField(
            model_name="recurso",
            name="nombre_recurso",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="recurso",
            name="tipo_recurso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="education.tiporecurso"
            ),
        ),
        migrations.AlterField(
            model_name="recurso",
            name="url_recurso",
            field=models.URLField(max_length=1000),
        ),
    ]
