# Generated by Django 5.2 on 2025-05-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('admin_id', models.AutoField(help_text='Identificador único del administrador.', primary_key=True, serialize=False)),
                ('username_admin', models.CharField(help_text='Nombre de usuario único del administrador.', max_length=30, unique=True)),
                ('email_admin', models.EmailField(help_text='Correo electrónico único del administrador.', max_length=15, unique=True)),
                ('password_admin', models.CharField(help_text='Contraseña del administrador (hasheada).', max_length=255)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='DocenteModel',
            fields=[
                ('id_docente', models.AutoField(help_text='Identificador único del docente.', primary_key=True, serialize=False)),
                ('nombre_docente', models.CharField(help_text='Nombre del docente.', max_length=30)),
                ('apellidos_docente', models.CharField(help_text='Apellidos del docente.', max_length=30)),
                ('email_docente', models.EmailField(help_text='Correo electrónico del docente.', max_length=15)),
                ('password_docente', models.CharField(help_text='Contraseña del docente (hasheada).', max_length=255)),
                ('ci_docente', models.CharField(help_text='Número de cédula de identidad único del docente.', max_length=9, unique=True)),
                ('telefono_docente', models.IntegerField(help_text='Número de elular del docente', max_length=8)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='EstudianteModel',
            fields=[
                ('id_estudiante', models.AutoField(help_text='Identificador único del estudiante.', primary_key=True, serialize=False)),
                ('nombre_estudiante', models.CharField(help_text='Nombre del estudiante.', max_length=30)),
                ('apellidos_estudiante', models.CharField(help_text='Apellidos del estudiante.', max_length=30)),
                ('email_estudiante', models.EmailField(help_text='Correo electrónico del estudiante.', max_length=15)),
                ('password_estudiante', models.CharField(help_text='Contraseña del estudiante (hasheada).', max_length=255)),
                ('ci_estudiante', models.CharField(help_text='Número de cédula de identidad único del estudiante.', max_length=9, unique=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
