# Generated by Django 5.2 on 2025-05-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(help_text='Identificador único del docente.', primary_key=True, serialize=False)),
                ('nombre_docente', models.CharField(help_text='Nombre del docente.', max_length=30)),
                ('apellidos_docente', models.CharField(help_text='Apellidos del docente.', max_length=30)),
                ('email_docente', models.EmailField(help_text='Correo electrónico del docente.', max_length=15)),
                ('password_docente', models.CharField(help_text='Contraseña del docente (hasheada).', max_length=255)),
                ('ci_docente', models.CharField(help_text='Número de cédula de identidad único del docente.', max_length=9, unique=True)),
                ('telefono_docente', models.IntegerField(help_text='Número de elular del docente')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.RenameModel(
            old_name='AdminModel',
            new_name='Admin',
        ),
        migrations.RenameModel(
            old_name='EstudianteModel',
            new_name='Estudiante',
        ),
        migrations.DeleteModel(
            name='DocenteModel',
        ),
    ]
