# Generated by Django 5.2 on 2025-05-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_docente_rename_adminmodel_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email_admin',
            field=models.EmailField(help_text='Correo electrónico único del administrador.', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password_admin',
            field=models.CharField(help_text='Contraseña del administrador (hasheada).', max_length=15),
        ),
        migrations.AlterField(
            model_name='docente',
            name='email_docente',
            field=models.EmailField(help_text='Correo electrónico del docente.', max_length=30),
        ),
        migrations.AlterField(
            model_name='docente',
            name='password_docente',
            field=models.CharField(help_text='Contraseña del docente (hasheada).', max_length=15),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email_estudiante',
            field=models.EmailField(help_text='Correo electrónico del estudiante.', max_length=30),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='password_estudiante',
            field=models.CharField(help_text='Contraseña del estudiante (hasheada).', max_length=15),
        ),
    ]
