# Generated by Django 5.2 on 2025-05-19 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_admin_email_admin_alter_admin_password_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.AutoField(help_text='Identificador de usuario', primary_key=True, serialize=False)),
                ('username_user', models.CharField(help_text='Nombre de usuario', max_length=30)),
                ('password_user', models.CharField(help_text='Contraseña del usuario', max_length=15)),
                ('email_user', models.EmailField(help_text='Correo electrónico del usuario.', max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la cuenta del usuario está activa')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro del usuario')),
                ('last_login', models.DateTimeField(blank=True, help_text='Fecha y hora del último inicio de sesión', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='email_admin',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password_admin',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='username_admin',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='email_docente',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='password_docente',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='email_estudiante',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='password_estudiante',
        ),
        migrations.AddField(
            model_name='admin',
            name='user_id',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
        migrations.AddField(
            model_name='docente',
            name='user_id',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user_id',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
    ]
