# Generated by Django 5.2 on 2025-05-19 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usuario_remove_admin_email_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
    ]
