# Generated by Django 5.2 on 2025-05-19 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_admin_user_id_alter_docente_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user_id',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='user_id',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='user_id',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
    ]
