# Generated by Django 5.2 on 2025-05-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_admin_user_id_alter_docente_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
