# Generated by Django 5.2 on 2025-05-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_usuario_user_id_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_id',
            field=models.AutoField(help_text='Identificador de usuario', primary_key=True, serialize=False),
        ),
    ]
