# Generated by Django 5.2 on 2025-05-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_admin_user_id_remove_docente_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='docente',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
