# Generated by Django 5.2 on 2025-05-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_admin_user_id_docente_user_id_estudiante_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
