# Generated by Django 5.2 on 2025-05-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.AutoField(help_text='Identificador de usuario', primary_key=True, serialize=False)),
                ('username_user', models.CharField(help_text='Nombre de usuario', max_length=30)),
                ('password_user', models.CharField(help_text='Contraseña del usuario', max_length=15)),
                ('email_user', models.EmailField(help_text='Correo electrónico del usuario.', max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la cuenta del usuario está activa')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro del usuario')),
                ('last_login', models.DateTimeField(blank=True, help_text='Fecha y hora del último inicio de sesión', null=True)),
            ],
        ),
    ]
