# Generated by Django 5.2 on 2025-05-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_admin_user_id_alter_docente_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password_user',
            field=models.CharField(help_text='Contraseña del usuario', max_length=130),
        ),
    ]
